language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y qstat intltool
  - ./autogen.sh

script:
  - ./configure --with-qstat=quakestat
  - make

notifications:
  irc: "chat.freenode.net#xqf"
  on_success: change
  on_failure: always
